##

In [1]:
from matplotlib import pyplot as plt
import numpy as np
import torch

import torchvision
from torchvision import datasets, transforms

from collections import Counter
from torch.utils.data import random_split

In [13]:
seed = 10
torch.manual_seed(seed)

category_index_manual = 8
n_val = 5000

data_path_manual = '/cifar-10-batches-py'

Function for loading the Cifar10 dataset.

The method will have to be run twice. The first time we load it as tensors and split the set between training, validation, and testing. We only want to identify one type of image (ships), so we get the labels of all the images and set all to "false" if they are not ships.

After running the method for the first time we get create a normalizer from the std and mean of the images. The method is then ran for a second time with the normalizer as the preprocessor.

In [15]:
def load_dataset(n_val, category_index, data_path, preprocessor):
    transformed_cifar10_train_val = datasets.CIFAR10(
        data_path,
        train=True,
        download=False,
        transform = preprocessor
    )

    transformed_cifar10_test = datasets.CIFAR10(
        data_path,
        train=False,
        download=False,
        transform = preprocessor

    )


    n_train = len(transformed_cifar10_train_val)-n_val

    transformed_cifar10_train_split, transformed_cifar10_val_split = random_split(
        transformed_cifar10_train_val,
        [n_train, n_val],

        generator=torch.Generator().manual_seed(seed)
    )

    print("Size of the train dataset:        ", len(transformed_cifar10_train_split))
    print("Size of the validation dataset:   ", len(transformed_cifar10_val_split))
    print("Size of the test dataset:         ", len(transformed_cifar10_test))

load_dataset(n_val, category_index_manual, data_path_manual, preprocessor=transforms.ToTensor())

C:\Users\osten\AppData\Local\Temp\ipykernel_24708\3165530937.py:21: FutureWarning: The input object of type 'Tensor' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Tensor', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  train_labels = np.array(transformed_cifar10_train_val)
C:\Users\osten\AppData\Local\Temp\ipykernel_24708\3165530937.py:21: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  train_labels = np.array(transformed_cifar10_train_val)
C:\Users\osten\AppData\Local\T

Size of the train dataset:         45000
Size of the validation dataset:    5000
Size of the test dataset:          10000


C:\Users\osten\AppData\Local\Temp\ipykernel_24708\3165530937.py:25: FutureWarning: The input object of type 'Tensor' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Tensor', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  test_labels = np.array(transformed_cifar10_test)
C:\Users\osten\AppData\Local\Temp\ipykernel_24708\3165530937.py:25: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  test_labels = np.array(transformed_cifar10_test)
C:\Users\osten\AppData\Local\Temp\ipykerne

In [ ]:
train_labels = np.array(transformed_cifar10_train_val)
train_labels = np.array(train_labels == category_index).astype(int)

test_labels = np.array(transformed_cifar10_test)
test_labels = np.array(test_labels == category_index).astype(int)


Creating a normalizer for the dataset around the mean and standard deviation of the 3 dimensions (height, width channel (color)).

Loading the dataset and applying the composition of transforms.

In [ ]:
imgs = torch.stack([img for img, _ in transformed_cifar10_train_val])

normalizer = transforms.Normalize(mean = imgs.mean(dim=(0, 2, 3)), std = imgs.std(dim=(0, 2, 3)))



Choosing a pre-trained CNN model. We choose ResNet18, which is not trained Cifar-10.

In [ ]:
from torchvision import models
import torch.nn as nn
import torch.optim as optim

In [ ]:
# Loading pre-trained ResNet18 model
model = models.resnet18(pretrained=True)

# Modify the last layer for binary classification
# Legg til markdown om at vi løser det som binary classification
num_features = model.fc.in_features
model.fc = nn.Linear(num_features,1)

# "Remember to use a suitable loss function like Binary Cross Entropy with Logits Loss (BCEWithLogitsLoss) and an optimizer like Adam or SGD for training.
loss_function = nn.BCEWithLogitsLoss()

# Legge til spørsmål om vi burde bruke SGD, Adam, RMSprop eller noe annet
# Legge til spørsmål om vi burde endre på learning raten, eller i alle fall forklare hvorfor vi bruker den vi bruker
optimizer = optim.adam(model.parameters(),  lr=0.001)

In [5]:
Counter([label for _, label in cifar10_train])

Counter({3: 4504,
         4: 4510,
         2: 4504,
         1: 4471,
         9: 4520,
         8: 4506,
         0: 4513,
         6: 4517,
         7: 4505,
         5: 4450})

In [6]:
imgs = torch.stack([img for img, _ in tensor_cifar10_train_val])
print(imgs.shape)

torch.Size([50000, 3, 32, 32])


Creating a normalizer for the dataset around the mean and standard deviation of the 3 dimensions (height, width channel (color)).

In [7]:
normalizer = transforms.Normalize(mean = imgs.mean(dim=(0, 2, 3)), std = imgs.std(dim=(0, 2, 3)))

Loading the dataset and applying the composition of transforms.

Attempt at plotting the normalized images.

In [8]:
img_t = tensor_cifar10_train_val.data[1]
print(img_t)
print("halla")
print(img_t.data)

[[[154 177 187]
  [126 137 136]
  [105 104  95]
  ...
  [ 91  95  71]
  [ 87  90  71]
  [ 79  81  70]]

 [[140 160 169]
  [145 153 154]
  [125 125 118]
  ...
  [ 96  99  78]
  [ 77  80  62]
  [ 71  73  61]]

 [[140 155 164]
  [139 146 149]
  [115 115 112]
  ...
  [ 79  82  64]
  [ 68  70  55]
  [ 67  69  55]]

 ...

 [[175 167 166]
  [156 154 160]
  [154 160 170]
  ...
  [ 42  34  36]
  [ 61  53  57]
  [ 93  83  91]]

 [[165 154 128]
  [156 152 130]
  [159 161 142]
  ...
  [103  93  96]
  [123 114 120]
  [131 121 131]]

 [[163 148 120]
  [158 148 122]
  [163 156 133]
  ...
  [143 133 139]
  [143 134 142]
  [143 133 144]]]
halla


In [9]:
print(tensor_cifar10_train_val)

Dataset CIFAR10
    Number of datapoints: 50000
    Root location: /cifar-10-batches-py
    Split: Train
    StandardTransform
Transform: ToTensor()


In [10]:
plt.imshow(img_t.permute(1, 2, 0))
plt.show()

AttributeError: 'numpy.ndarray' object has no attribute 'permute'